# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout: &checkout
    docker:
      # specify the version you desire here
      - image: circleci/node:8.1-browsers

    working_directory: ~/repo

    steps:
      - checkout
  restore_cache:
    <<: *checkout
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
  build:
    <<: *checkout
    steps:
      - run: npm install
  save_cache:
    <<: *checkout
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    <<: *checkout
    steps:
      - run: npm run lint
  test:
    <<: *checkout
    steps:
      - run: npm test

workflows:
  version: 2
  build_and_release:
    jobs:
      - checkout
      - restore_cache:
          requires:
            - checkout
      - build:
          requires:
            - restore_cache
      - save_cache:
          requires:
            - build
          filters:
            branches:
              only: master
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
