version: 2
jobs:
  build: &build
    docker:
      - image: circleci/node:8.1-browsers

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-dependencies-{{ .Branch }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
  lint:
    <<: *build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-dependencies-{{ .Branch }}
      - run: npm run lint
  test:
    <<: *build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-dependencies-{{ .Branch }}
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
